[tool.poetry]
name = "iamcompact-nomenclature"
version = "0.1.0"
description = "Data structure definition for validation of model outputs in the HORIZON EUROPE project IAM COMPACT, using nomenclature-iamc"
authors = ["Jan Ivar Korsbakken <janko@cicero.oslo.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
nomenclature-iamc = ">=0.14.0"
pyam-iamc = ">=2.0"

[tool.poetry.group.dev.dependencies]
ipython = ">=8.20.0"
pytest = ">=8.0.0"
ipykernel = ">=6.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
